services:
  oficina-app:
    build:
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"      
    container_name: oficina-app
    ports:
      - "5173:5173"
      - "9003:9003"
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - oficina

  oficina-nginx:
    image: nginx:alpine
    container_name: oficina-nginx
    ports:
      - "4500:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - oficina-app
    networks:
      - oficina

  # oficina-db:
  #   image: mysql:8.0
  #   container_name: oficina-db
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: oficina
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_USER: oficina
  #     MYSQL_PASSWORD: secret
  #   ports:
  #     - "4501:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   networks:
  #     - oficina

  oficina-mail-server:
    image: 'axllent/mailpit:latest'
    container_name: oficina-mail-server
    ports:
      - '4502:1025'
      - '4503:8025'
    networks:
      - oficina

networks:
  oficina:

    # volumes:
    #   mysql_data:
